apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: loki
  name: loki
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: loki
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: loki
    spec:
      containers:
        - args:
            - -config.file=/etc/loki/local-config.yaml
          image: grafana/loki:latest
          name: loki
          ports:
            - containerPort: 3100
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: data
      restartPolicy: Always
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: loki-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: loki
  name: loki
  namespace: monitoring
spec:
  ports:
    - name: "3100"
      port: 3100
      targetPort: 3100
  selector:
    io.kompose.service: loki
status:
  loadBalancer: {}

