kind: PersistentVolume
apiVersion: v1
metadata:
  name: apps-logs
  namespace: monitoring
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/vagrant/logs"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apps-logs
  namespace: monitoring
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: apps-logs

