apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: promtail
  name: promtail
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: promtail
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: promtail
    spec:
      containers:
        - args:
            - -config.file=/etc/promtail/config.yml
          image: grafana/promtail:2.4.2
          name: promtail
          resources: {}
          volumeMounts:
            - mountPath: /vagrant/logs
              name: apps-logs-pv
      restartPolicy: Always
      volumes:
        - name: apps-logs
          persistentVolumeClaim:
            claimName: apps-logs-pvc
status: {}