{
 "title": "Loki and Fluentbit",
 "description": "Prometheus Fluentbit exporter metrics.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Loki", "label": "datasource", "query": "loki" },
   {
    "name": "instance",
    "label": "instance",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Fluent-bit input bytes/s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "count_over_time({instance=\"$instance\"} |= `200` [$__interval])"
    }
   ]
  },
  {
   "title": "Fluent-bit input records",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Fluent-bit output bytes/s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(fluentbit_output_proc_bytes_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Fluent-bit output records",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {}
   ]
  },
  {
   "title": "Fluent-bit input files",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_files_closed_total{instance=~\"$instance\"}[1m]))",
     "legendFormat": "Closed {{ name }}"
    },
    {
     "expr": "sum(rate(fluentbit_input_files_opened_total{instance=~\"$instance\"}[1m]))",
     "legendFormat": "Opened {{ pod }}"
    },
    {
     "expr": "sum(rate(fluentbit_input_files_rotated_total{instance=~\"$instance\"}[1m]))",
     "legendFormat": "Rotated {{ pod }}"
    }
   ]
  },
  {
   "title": "Fluent-bit filters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_filter_add_records_total{instance=~\"$instance\"}[1m]))",
     "legendFormat": "Add {{ name }}"
    },
    {
     "expr": "sum(rate(fluentbit_filter_drop_records_total{instance=~\"$instance\"}[1m]))",
     "legendFormat": "Drop {{ pod }}"
    }
   ]
  },
  {
   "title": "Fluent-bit errors and retires",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_errors_total{instance=~\"$instance\"}[1m]))",
     "legendFormat": "Errors {{ name }}"
    },
    {
     "expr": "sum(rate(fluentbit_output_retries_failed_total{instance=~\"$instance\"}[1m]))",
     "legendFormat": "Retries failed {{ pod }}"
    },
    {
     "expr": "sum(rate(fluentbit_output_retries_total{instance=~\"$instance\"}[1m]))",
     "legendFormat": "Retries {{ pod }}"
    }
   ]
  }
 ]
}