kind: Secret
apiVersion: v1
metadata:
  name: fluent-bit-fluent-bit-loki-token-tzpcx
  namespace: fluentbit
  uid: 5e2d8222-8146-4aef-b8f8-b5b0a88ba111
  resourceVersion: '1735'
  creationTimestamp: '2022-10-14T19:32:32Z'
  annotations:
    kubernetes.io/service-account.name: fluent-bit-fluent-bit-loki
    kubernetes.io/service-account.uid: eebb127b-b4fb-4c90-a8b4-461e3d72b6db
  managedFields:
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2022-10-14T19:32:32Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:ca.crt: {}
          f:namespace: {}
          f:token: {}
        f:metadata:
          f:annotations:
            .: {}
            f:kubernetes.io/service-account.name: {}
            f:kubernetes.io/service-account.uid: {}
        f:type: {}
data:
  ca.crt: >-
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1UQXhOREU1TVRreU9Wb1hEVE15TVRBeE1URTVNVGt5T1Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTHI5ClVVVGppWU54aHFia1E3T0g3Y1VnWnpBajFuVHJ6MTdsNHIzcGVTaWpzaWZCSWwxMmdKRStEZVJQL1dqMHBGN0gKYTFEcllxQmFreHVpY3RhQ1c3S21kWWk5Wm1RVnJUanBQTVNMMFcxTHFvVU9mZkcvbTU4bHZuTVB3dVVZb21VZQpOQWJLZGZsOStzdVFwOXBkRS83OS80dlM0VkFuSUNFa1ZkeVlHUUEvM1hyUEZ1TGYybFhXYXhOMENoTEc5bGI5CkQ1ZW5kSnlkMklwT1p6akRHMW5sUTRyaXhhZnZtOGJzTE9KYTdHcjNqaGlHRDY4Q0M3ZEhuWXU1Y0phWldCbUsKdkNhbG95eFIwRlZRUWRsY2lGdjJpcmEvZVRuNzE1ZWhVOVBxcWNpQVFnOSswY01zdGhwYWlHWk9QOU5HNHdEbAowOWVBT1MzQ25XdkgwTm83MlMwQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZPSnBQVjFiYkFDZWpPQ0JJak9ILzlRUi9pK3hNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSUZGN1MvTVVZMnFHU2dNUGtwUAp2QzBORTNsVmNKbGFuV0pWaVJNSUJJUy9sWDVaWVlhUUxUL3ZtWFpqeWNJMGEvNW0wdVZjbU1DVmpQcWNhTENyClJweklvWWhSRDdkNFpmOGFDYTJWMExYR0lFRy9TOGNKWUZFaFRkQVNjTmlYSVV0RGhJdndwVFNRYitWazFxbmYKRVJLRXRoVUtuNGhCM1JHSGE3WjlLMVhlRFVWVjRFdFFDcXg4VHZCOFhjeWFabG1qWUpYNG5iTmo3N1dBbkdRMQozSmdldW52WXE0cGpDb1kwcmhUZ2RTZnprdzdZUTdhblJvU1dYVmZ2bmIreHhRNDJqZ05mMFVzTmh3UnBOQ3dDCjF1TzJJOTI5VEVwQXcrS2o4dVZyeUVwVlMxMDVOV3N1Q3AwT0I3cjdyK2pqczVpSUpUc1lkcFY5RjJaNnFMV2kKTkpZPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  namespace: Zmx1ZW50Yml0
  token: >-
    ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklrMVRSVzVpYmt0bU0zUjBhRzFQY1c1NlJVWkJVVk5mTW5oVlkwNURlbXBJU0ZsbE1uTTBRM0EyTkRnaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUprWldaaGRXeDBJaXdpYTNWaVpYSnVaWFJsY3k1cGJ5OXpaWEoyYVdObFlXTmpiM1Z1ZEM5elpXTnlaWFF1Ym1GdFpTSTZJbVpzZFdWdWRDMWlhWFF0Wm14MVpXNTBMV0pwZEMxc2IydHBMWFJ2YTJWdUxYUjZjR040SWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXpaWEoyYVdObExXRmpZMjkxYm5RdWJtRnRaU0k2SW1ac2RXVnVkQzFpYVhRdFpteDFaVzUwTFdKcGRDMXNiMnRwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXpaWEoyYVdObExXRmpZMjkxYm5RdWRXbGtJam9pWldWaVlqRXlOMkl0WWpSbVlpMDBZemt3TFdFNFlqUXRORFl4WlROa056SmlObVJpSWl3aWMzVmlJam9pYzNsemRHVnRPbk5sY25acFkyVmhZMk52ZFc1ME9tUmxabUYxYkhRNlpteDFaVzUwTFdKcGRDMW1iSFZsYm5RdFltbDBMV3h2YTJraWZRLmwzc1hlVDhEV3puSEFvSThpOEJ2YUZfcWJCLXZrMlFXa1FKSEdwVTJQckoxdzhRVFUtNVpLdk9zTURTMW5sZUhPRW5sbkw1c1NTWFBsZ3phUGV1U2NOaE5FdVhrWU91blZhWWtPSVdYYWRtWU4yNVJXdVMwci16amJweENYb3haSnExRE5ya2I2Nm10WFFJSzVScHhDUUt2My1GX3lPZi0yTzMxVnliUEN3dDh4elVMaUNlTG9XMHdQY2lYMGhBOXJKMTh4eG1vOV9ramo5RGRLMFpSblg0OFFaTVhuVHhWZmJMOWlHN0R5anJzZk9oX1BnV1VpRlBHN2ZNRnVSR3FzeVNUaGt4Mm5xQlFJYlFXZGRqZm5jRUlSRWJZV21GcmZMQ1o0RU9yWHlkZk55M2VURnBQekg4STRkRmt4VDhvVFAxN3Ewbl8zMEY0dWtvNG5CTHliZw==
type: kubernetes.io/service-account-token
