kind: ServiceAccount
apiVersion: v1
metadata:
  name: fluent-bit-fluent-bit-loki
  namespace: fluentbit
  uid: eebb127b-b4fb-4c90-a8b4-461e3d72b6db
  resourceVersion: '1737'
  creationTimestamp: '2022-10-14T19:32:32Z'
  labels:
    app: fluent-bit-loki
    app.kubernetes.io/managed-by: Helm
    chart: fluent-bit-2.3.1
    heritage: Helm
    release: fluent-bit
  annotations:
    meta.helm.sh/release-name: fluent-bit
    meta.helm.sh/release-namespace: fluentbit
  managedFields:
    - manager: helm
      operation: Update
      apiVersion: v1
      time: '2022-10-14T19:32:32Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app: {}
            f:app.kubernetes.io/managed-by: {}
            f:chart: {}
            f:heritage: {}
            f:release: {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2022-10-14T19:32:32Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:secrets:
          .: {}
          k:{"name":"fluent-bit-fluent-bit-loki-token-tzpcx"}: {}
secrets:
  - name: fluent-bit-fluent-bit-loki-token-tzpcx